---
title: Clawfire's Blog
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: drafts
  values:
    layout: post
name: Your New Jekyll Site
description: Blogging about stuffs
meta_description: Your New Jekyll Site, Blogging about stuffs
aboutPage: true
markdown: redcarpet
highlighter: pygments
paginate: 20
baseurl: "/"
domain_name: http://clawfire.net
google_analytics: UA-XXXXXXXX-X
disqus: false
disqus_shortname: your-disqus-shortname
url: http://clawfire.net
author: Clawfire
authorTwitter: clawfire
permalink: "/:year/:title/"
