---
title: Mediator
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Clawfire's Blog"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: clawfire@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Thibault Milan'
author: 'Thibault Milan'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://clawfire.net" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@clawfire'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/clawfire
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/clawfire
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
