---
title: "Clawfire's Blog"
timezone: "Europe/Brussels"
collections:
  posts:
    title: "Posts"
    output: true
  uploads:
    title: "Uploads"
    output: true
gems:
- gemoji
- jekyll-paginate
description: "Billets d'humeurs, LGBT, geek, ... un peu de moi en somme."
email: "clawfire@gmail.com"
logo_image: "/assets/images/me.jpg"
cover_image: "/assets/images/otqvwecws8o-dan-carlson.jpg"
name: "Thibault Milan"
author: "Thibault Milan"
author_image: "/assets/images/me.jpg"
paginate: 5
url: "http://clawfire.net"
baseurl:
twitter_handle: "@clawfire"
flattr_id: "8dx10l"
social:
- icon: "twitter"
  url: "https://twitter.com/clawfire"
  desc: "Follow me on twitter"
  share_url: "http://twitter.com/share"
  share_title: "?text="
  share_link: "&amp;url="
- icon: "github"
  url: "https://github.com/clawfire"
  desc: "Fork me on github"
  share_url:
  share_title:
  share_link:
- icon: "lastfm"
  url: "http://www.last.fm/user/clawfire"
  desc: "What you see is what I listen"
  share_url:
  share_title:
  share_link:
