---
title: Clawfire's Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
gems:
- jemoji
- jekyll-paginate
description: |
  A Jekyll theme - Medium inspired
email: clawfire@gmail.com
logo: "/assets/images/df_logo.jpg"
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"
name: Thibault Milan
author: Thibault Milan
author_image: "/assets/images/author.jpg"
paginate: 5
url: http://clawfire.net
baseurl: 
twitter_handle: "@clawfire"
social:
- icon: twitter
  url: https://twitter.com/clawfire
  desc: Follow me on twitter
  share_url: http://twitter.com/share
  share_title: "?text="
  share_link: "&amp;url="
- icon: github
  url: https://github.com/clawfire
  desc: Fork me on github
  share_url: 
  share_title: 
  share_link: 
